apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hrvq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hrvq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hrvq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hrvq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hrvq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-unvn-tenant/rhtap-demo-app/hacbs-test-project-hrvq@sha256:fb1162d8dbce1f6e1f627a8447e43e60ddb1779a3bab0fdf8e141ceda6b67d90
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
